import "@/styles/global.css"
import Header from "@/components/Header"
import { Inter } from "next/font/google"
import Banner from "@/components/Banner"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="max-w-7xl mx-auto">
        <Header />
        <Banner />
        {/* Todo Banner */}
        {children}
      </body>
    </html>
  )
}
